config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'static#index'
  root 'admins#new'

 	resources :admins, only: [:new, :create]
  	get "/get_user" => "static#index"
  	post '/admins' => 'admins#create'

  	get 'signup' => 'admins#new'
  	get '/login' => 'sessions#new'
  	post '/login' => 'sessions#create'
  	get '/logout' => 'sessions#destroy'

 	resources :sentiment_results, only: [:index, :create]
 	resources :filtered_results, only: [:index, :create]
  resources :tweets, only: [:create]

  resources :users do
  	resources :tweets, only: [:index, :destroy]
  	resources :sentiment_results, only: [:show, :destroy]
  	resources :filtered_results, only: [:show, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filtered_result.rb
class FilteredResult < ApplicationRecord
	belongs_to :tweet
end

app/models/sentiment_result.rb
class SentimentResult < ApplicationRecord

	belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user
	has_one :filtered_result, dependent: :destroy

	
end

app/models/user.rb
class User < ApplicationRecord

	has_many :tweets, dependent: :destroy
	has_one :filtered_result, through: :tweet, dependent: :destroy
	has_one :sentiment_result, dependent: :destroy
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

	def new
		@admin = Admin.new
	end

	def create
		@admin =  Admin.new(admin_params)
		if @admin.save
			session[:admin_id] = @admin.id 
			redirect_to '/get_user'
		else
			redirect_to '/'
		end
	end

	private
	def admin_params
        params.require(:admin).permit(:name, :email, :password)		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception 
  include AdminsHelper
end

app/controllers/filtered_results_controller.rb
class FilteredResultsController < ApplicationController 
	before_action :require_login,  only: [:index, :create]

	def index
	end

	def create
		
		User.all.each do |user|
			@negative_tweets_array = []
			@negative_tweets = user.tweets.where(polarity: ":(")
			@negative_tweets.each do |tweet|
				@negative_tweets_array << tweet.text # getting negative tweets by this user
			end

			if @negative_tweets_array.count > 0
				@result = Monkeylearn.classifiers.classify('cl_Y8MidxpP', @negative_tweets_array, sandbox: true)
			
				@count = 0 # negative tweet count
				@suicidal_count = 0
				@probability = 0

				@negative_tweets.each do |tweet| # iterating all negative tweets and create filtered_result and calculating suicidal count and probability. 
					FilteredResult.create_with(tweet_id: tweet.id, label: @result.result[@count].first["label"], probability: @result.result[@count].first["probability"]).find_or_create_by(tweet_id: tweet.id)

					if tweet.filtered_result.label == "suicidal" 
						@suicidal_count += 1
						@probability += tweet.filtered_result.probability
					end
					@count += 1
				end

				if @suicidal_count > 0
					tweet_count = user.tweets.count
					suicidal_count_percent = (@suicidal_count / tweet_count.to_f) * 100
					average = @probability / @suicidal_count
					suicidal_index = suicidal_count_percent * average
					user.update(suicidal_tweet_count: @suicidal_count, suicidal_tweets_probability_average: average, suicidal_index: suicidal_index)
				else
					user.update(suicidal_tweet_count: @suicidal_count, suicidal_tweets_probability_average: 0, suicidal_index: 0)
				end
			else # no negative tweets
				user.update(suicidal_tweet_count: 0, suicidal_tweets_probability_average: 0, suicidal_index: 0)
			end
		end
		redirect_to '/get_user'
	end

	def require_login
		unless logged_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/'
		end
	end

end

app/controllers/sentiment_results_controller.rb
class SentimentResultsController < ApplicationController 
	before_action :require_login,  only: [:index, :create, :show]

	def index
		@all_sentiment = SentimentResult.all
	end

	def show
		@user = User.find(params[:user_id])
		@sentiment = SentimentResult.find_by(user_id: @user.id)
	end

	def create
		User.all.each do |user|
			pos_result = user.tweets.where(polarity: ":)").average(:polarity_confidence)
			neg_result = user.tweets.where(polarity: ":(").average(:polarity_confidence)
			SentimentResult.create_with(user_id: user.id, positive_average: pos_result, negative_average: neg_result).find_or_create_by(user_id: user.id)
		end
		 redirect_to sentiment_results_path
	end

	private
	def require_login
		unless logged_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/'
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@admin = Admin.find_by(email: params[:email])
		if @admin and @admin.authenticate(params[:password])
			session[:admin_id] = @admin.id 
			redirect_to get_user_path
		else
			flash[:alert] = "Please enter a valid username or password"
			redirect_to '/login'
		end	
	end

	def destroy 
		session[:admin_id] = nil
		redirect_to '/login'
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	before_action :require_login,  only: [:index]
	def index
	end

	private
	def require_login
		unless logged_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/'
		end
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :set_twitter_client
	before_action :require_login,  only: [:index, :create]

	def create
		User.all.each do |user|
			@tweets = get_tweets(user.id)
			if user.tweets.count == 0 # new user have no tweet
				@tweets.each do |tweet|
					CreateTweetsJob.perform_later(user.id, tweet.full_text, tweet.id)
				end
			else
				@tweets.each do |tweet|
				# prevent duplicate tweets being store in database
					if user.tweets.pluck(:twitter_tweet_id).include?(tweet.id.to_s)
					else
						CreateTweetsJob.perform_later(user.id, tweet.full_text, tweet.id)
					end
				end
			end
		end
		redirect_to '/users'
	end

	private

	def get_tweets(id)
		@user = User.find(id)		
		x = @twitter.user_timeline(@user.twitter_user_id.to_i)
		last_id = x.last.id  
		@tweets = []
		@tweets << x
	
		# looping through tweets to get more than 200 tweets per query
		i = 1
		while i <= 1 do
			@tweets << @twitter.user_timeline(@user.twitter_user_id.to_i, count: 20, max_id: last_id)
	    	last_id = @tweets.last.last.id
	    	i += 1
		end
		return @tweets.flatten
	end

	def require_login
		unless logged_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/'
		end
	end

	def set_twitter_client
		@twitter = AngelAi::Application.config.twitter
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_twitter_client
	before_action :require_login,  only: [:index, :create, :show]

	def create
		if params[:search].split.count > 0 and params[:search].split.count < 11
			@users = @twitter.search(params[:search], lang:"en").take(2)
			@users.each do |user|
				User.find_or_create_by(screen_name: user.user.screen_name, twitter_user_id: user.user.id)
			end
			redirect_to users_path
		else
			@error = "Invalid search input, please try again"
			render "static/index"
		end
	end

	def index
		@users
	end

	def show 
		@user = User.find(params[:id])
	end

	private

	def set_twitter_client
		@twitter = AngelAi::Application.config.twitter
	end

	def require_login
		unless logged_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/'
		end
	end

end

app/helpers/admins_helper.rb
module AdminsHelper
	def current_user
		@current_user ||= Admin.find(session[:admin_id]) if session[:admin_id]
	end

	def logged_in?
		!current_user.nil?
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filtered_results_helper.rb
module FilteredResultsHelper
end

app/helpers/sentiment_results_helper.rb
module SentimentResultsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sentiment_results/index.html.erb
<div>
	<h3 style="text-align:center;"> Bar Chart depicting the average postitive tweets and average negative tweets per user </h3>
</div>	
<br>

<div class="row">
<% @all_sentiment.each do |sentiment| %>
  <div class="col-md-1"></div>
  <div class="col-md-5">
    <div class='sentiment-table' data-positive='<%= sentiment.positive_average %>' data-negative='<%= sentiment.negative_average %>' data-name='<%=User.find(sentiment.user_id).screen_name%>'%>
    </div>
  </div>
  
<% end %>
</div>
<div class="col-md-1"></div>
<div class="col-md-5">
<%= form_tag(filtered_results_path, method: "post", class: 'form-overlay') do %>
	<%= submit_tag("Final Suicidal Analysis", id: 'result-btn', class: 'btn btn-primary') %>  
  </div>
<% end %>
    <!--Load the AJAX API-->
<!-- <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> -->

<script type="text/javascript">


  // Set a callback to run when the Google Visualization API is loaded.
  	google.charts.setOnLoadCallback(drawChart);

  // Callback that creates and populates a data table,
  // instantiates the bar chart, passes in the data and
  // draws it.
  	function drawChart() {
  		divs = document.getElementsByClassName('sentiment-table');
  		Array.prototype.forEach.call(divs, function(div, index){

    // Create the data table.
    	var data = new google.visualization.DataTable();
	    data.addColumn('string', 'Name');
	    data.addColumn('number', 'tweets');

	    data.addRows([
	      ['Avg. pos Tweets', parseFloat(div.getAttribute('data-positive'))],
	      ['Avg. neg Tweets', parseFloat(div.getAttribute('data-negative'))]
		]);

    // Set chart options
    var options = {'title':div.getAttribute('data-name'),
    				titleTextStyle: {fontSize: '20'},
                   'width':500,
                   'height':300};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.BarChart(div);
    chart.draw(data, options);

  	});
  	}
</script>

app/views/users/index.html.erb
<div class="row">
<div class="col-md-3"></div>
	<div class=col-md-6>
		<h2>Twitter Users in Database</h2>
		<table class="table table-bordered table-striped">
			<tr>
				<th>Twitter Username</th>
				<th>Tweets Analysed</th>
			</tr>
				<% @user = User.all %>
				<%@user.each do |user| %>
			<tr>
				<td><%= user.screen_name %></td>
				<td><%= user.tweets.count %></td>
			</tr>
			<%end%>
		</table>
		<%= form_tag(tweets_path, method: "post", class: 'form-overlay') do %>
			  <%= submit_tag("Create Tweets", class: 'btn btn-primary') %>
			<% end %>
			<hr>
		<% if User.pluck(:id).all? { |e| Tweet.pluck(:user_id).include?(e) } and User.first %>
				<%= form_tag(sentiment_results_path, method: "post") do %>
			  	<%= submit_tag("Analysed Tweets Sentiment", class: 'btn btn-primary') %>
				<% end %>
			<% end %>
	</div>
<div class="col-md-3"></div>
</div>